spring:
  application:
    name: gateway-service
  main:
    web-application-type: reactive

  cloud:
    gateway:
      routes:
        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/api/auth/**
          filters:
            - StripPrefix=1

        - id: projects-manager
          uri: lb://PROJECTS-MANAGER
          predicates:
            - Path=/api/projects/**
          filters:
            - StripPrefix=1

        - id: resources-manager
          uri: lb://RESOURCES-MANAGER
          predicates:
            - Path=/api/resources/**
          filters:
            - StripPrefix=1

        - id: tasks-manager
          uri: lb://TASKS-MANAGER
          predicates:
            - Path=/api/tasks/**
          filters:
            - StripPrefix=1

        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/api/users/**
          filters:
            - StripPrefix=1

  discovery:
    locator:
      enabled: true

eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    register-with-eureka: true

server:
  port: 8888
