spring:
  application:
    name: gateway-service
  main:
    web-application-type: reactive

  cloud:
    gateway:
      routes:
        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/api/auth/**  # Redirige les requêtes qui commencent par /api/auth/ vers USER-SERVICE
          filters:
            - StripPrefix=1  # Enlève le premier segment du chemin, utile si le service attend une URL sans `/api/auth`

  discovery:
    locator:
      enabled: true  # Active la découverte des services via Eureka

eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    register-with-eureka: true

server:
  port: 8888
