version: "3.8"
services:
  eureka-server:
    build:
      context: ./eureka-server
    ports:
      - "8761:8761"
    networks:
      - microservices-net

  gateway-service:
    build:
      context: ./gateway-service
    ports:
      - "8888:8888"
    depends_on:
      - eureka-server
    environment:
      - eureka.client.serviceUrl.defaultZone=http://eureka-server:8761/eureka/
    networks:
      - microservices-net

  project-service:
    build:
      context: ./Projects Manager
    ports:
      - "8081:8081"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://projectdb:3306/projects_db?createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true&useSSL=false
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/

    depends_on:
      projectdb:
        condition: service_healthy
    networks:
      - microservices-net

  resource-service:
    build:
      context: ./Ressources Manager
    ports:
      - "8083:8083"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://resourcedb:3306/resource_manager_db?createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true&useSSL=false
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/
    depends_on:
      resourcedb:
        condition: service_healthy
    networks:
      - microservices-net

  task-service:
    build:
      context: ./Tasks Manager
    ports:
      - "8082:8082"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://taskdb:3306/task_manager_db?createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true&useSSL=false
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/
    depends_on:
      taskdb:
          condition: service_healthy

    networks:
      - microservices-net

  user-service:
    build:
      context: ./user-service
    ports:
      - "8099:8099"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://userdb:3306/users_manager?createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true&useSSL=false
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/
    depends_on:
      userdb:
          condition: service_healthy
    deploy:
      restart_policy:
        condition: on-failure
    networks:
      - microservices-net

  projectdb:
    image: "mysql:latest"
    restart: always
    environment:
      MYSQL_DATABASE: project_manager_db
      MYSQL_ALLOW_EMPTY_PASSWORD: true
    volumes:
      - project-db:/var/lib/mysql
    networks:
      - microservices-net
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p1620" ]
      interval: 10s
      timeout: 5s
      retries: 5


  resourcedb:
    image: "mysql:latest"
    restart: always
    environment:
      MYSQL_DATABASE: resource_manager_db
      MYSQL_ALLOW_EMPTY_PASSWORD: true
    volumes:
      - resource-db:/var/lib/mysql
    networks:
      - microservices-net
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p1620" ]
      interval: 10s
      timeout: 5s
      retries: 5


  taskdb:
    image: "mysql:latest"
    restart: always
    environment:
      MYSQL_DATABASE: task_manager_db
      MYSQL_ALLOW_EMPTY_PASSWORD: true
    volumes:
      - task-db:/var/lib/mysql
    networks:
      - microservices-net
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p1620" ]
      interval: 10s
      timeout: 5s
      retries: 5


  userdb:
    image: "mysql:latest"
    restart: always
    environment:
      MYSQL_DATABASE: user_manager_db
      MYSQL_ALLOW_EMPTY_PASSWORD: true
    volumes:
      - user-db:/var/lib/mysql
    networks:
      - microservices-net
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p1620" ]
      interval: 10s
      timeout: 5s
      retries: 5


volumes:
  project-db:
  resource-db:
  task-db:
  user-db:

networks:
  microservices-net:
    driver: bridge
