server:
  port: 8080

spring:
  application:
    name: user-service
  datasource:
    url: jdbc:mysql://localhost:3308/users_manager?createDatabaseIfNotExist=true
    username: root
    password:
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: none
  flyway:
    baseline-on-migrate: true
    locations: classpath:db/migration

eureka:
  instance:
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/


security:
  jwt:
    secret-key: fghskjdx35cxc68c9WNC4567TF3456CGHHVTD34IFDWS
    expiration-time: 3600000